### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by dingraha** [byuflowlab/FLOWMath.jl#25]
Could I selfishly ask for a release for the new `cumtrapz` function? :-)

**Comment by andrewning** [comment]
Thanks for the reminder.  I didn't tag it because I noticed the documentation was failing (probably need to update PyPlot or something).  I've been super swamped these last few weeks.  I just gave you write access to the repo if you want to get to it sooner.

**Comment by dingraha** [comment]
@JuliaRegistrator register

**Comment by dingraha** [comment]
I think this is taken care of, thanks!
